In [1]:
import tensorflow as tf
import numpy as np

# Prepare Dataset for input into the model

In [2]:
import pandas as pd
from pathlib import Path

labeled_anomalies = pd.read_csv(
    Path("/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/labeled_anomalies.csv")
)
labeled_anomalies
labeled_anomalies.groupby("spacecraft")["chan_id"].nunique()

spacecraft
MSL     27
SMAP    54
Name: chan_id, dtype: int64

In [3]:
import numpy as np

for i, row in labeled_anomalies.iterrows():
    ch_id = labeled_anomalies["chan_id"][i]
    ch_data = np.load(
        Path(f"/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/train/{ch_id}.npy")
    )
    print(row["spacecraft"], ch_id, ch_data.shape)

SMAP P-1 (2872, 25)
SMAP S-1 (2818, 25)
SMAP E-1 (2880, 25)
SMAP E-2 (2880, 25)
SMAP E-3 (2880, 25)
SMAP E-4 (2880, 25)
SMAP E-5 (2880, 25)
SMAP E-6 (2880, 25)
SMAP E-7 (2769, 25)
SMAP E-8 (2880, 25)
SMAP E-9 (2880, 25)
SMAP E-10 (2880, 25)
SMAP E-11 (2880, 25)
SMAP E-12 (2880, 25)
SMAP E-13 (2880, 25)
SMAP A-1 (2880, 25)
SMAP D-1 (2849, 25)
SMAP P-2 (2821, 25)
SMAP P-3 (2855, 25)
SMAP D-2 (2880, 25)
SMAP D-3 (2880, 25)
SMAP D-4 (2833, 25)
SMAP A-2 (2648, 25)
SMAP A-3 (2736, 25)
SMAP A-4 (2690, 25)
SMAP G-1 (2820, 25)
SMAP G-2 (2478, 25)
SMAP D-5 (2561, 25)
SMAP D-6 (2594, 25)
SMAP D-7 (2583, 25)
SMAP F-1 (2869, 25)
SMAP P-4 (2609, 25)
SMAP G-3 (2624, 25)
SMAP T-1 (2875, 25)
SMAP T-2 (2855, 25)
SMAP D-8 (2602, 25)
SMAP D-9 (2583, 25)
SMAP F-2 (2861, 25)
SMAP G-4 (2551, 25)
SMAP T-3 (2876, 25)
SMAP D-11 (2611, 25)
SMAP D-12 (312, 25)
SMAP B-1 (2435, 25)
SMAP G-6 (2881, 25)
SMAP G-7 (2446, 25)
SMAP P-7 (2853, 25)
SMAP R-1 (2874, 25)
SMAP A-5 (705, 25)
SMAP A-6 (682, 25)
SMAP A-7 (2879, 25)
SMAP D-13 (1490, 25)
SMAP P-2 (2821, 25)
SMAP A-8 (762, 25)
SMAP A-9 (762, 25)
SMAP F-3 (2880, 25)
MSL M-6 (1565, 55)
MSL M-1 (2209, 55)
MSL M-2 (2208, 55)
MSL S-2 (926, 55)
MSL P-10 (4308, 55)
MSL T-4 (2272, 55)
MSL T-5 (2272, 55)
MSL F-7 (2511, 55)
MSL M-3 (2037, 55)
MSL M-4 (2076, 55)
MSL M-5 (2032, 55)
MSL P-15 (3682, 55)
MSL C-1 (2158, 55)
MSL C-2 (764, 55)
MSL T-12 (1145, 55)
MSL T-13 (1145, 55)
MSL F-4 (2244, 55)
MSL F-5 (2598, 55)
MSL D-14 (3675, 55)
MSL T-9 (439, 55)
MSL P-14 (2880, 55)
MSL T-8 (748, 55)
MSL P-11 (3969, 55)
MSL D-15 (2074, 55)
MSL D-16 (1451, 55)
MSL M-7 (1587, 55)
MSL F-8 (3342, 55)

In [4]:
ch_id = "E-10"
ch_data = np.load(
    Path(f"/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/train/{ch_id}.npy")
)
df = pd.DataFrame(ch_data)
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
count,2880.000000,2880.000000,2880.000000,2880.000000,2880.0,2880.000000,2880.000000,2880.000000,2880.000000,2880.000000,...,2880.0,2880.0,2880.000000,2880.000000,2880.000000,2880.0,2880.000000,2880.000000,2880.0,2880.0
mean,-0.587524,0.037500,0.007639,0.029167,0.0,0.171528,0.132986,0.001389,0.000694,0.000694,...,0.0,0.0,0.029167,0.029167,0.014583,0.0,0.039931,0.038889,0.0,0.0
std,0.808463,0.190017,0.087081,0.168303,0.0,0.377035,0.339619,0.037248,0.026348,0.026348,...,0.0,0.0,0.168303,0.168303,0.119899,0.0,0.195830,0.193364,0.0,0.0
min,-1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
25%,-1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
50%,-1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
75%,-1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0
max,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.0,0.0,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.0,0.0

In [5]:
ch_test_data = np.load(
    Path(f"/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/test/{ch_id}.npy")
)
df_test = pd.DataFrame(ch_test_data)
df_test.describe()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
count,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,...,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000,8505.000000
mean,-0.555936,0.022457,0.003410,0.018577,0.000235,0.108642,0.082305,0.000588,0.000235,0.000353,...,0.000118,0.000118,0.018577,0.018107,0.009406,0.000118,0.024809,0.023163,0.000118,0.000118
std,0.830252,0.148174,0.058297,0.135035,0.015334,0.311208,0.274844,0.024241,0.015334,0.018779,...,0.010843,0.010843,0.135035,0.133346,0.096534,0.010843,0.155552,0.150429,0.010843,0.010843
min,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
labeled_anomalies[labeled_anomalies["chan_id"] == "E-10"]

,chan_id,spacecraft,anomaly_sequences,class,num_values
11,E-10,SMAP,"[[5000, 5050], [5601, 5871]]","[contextual, contextual]",8505

In [7]:
import plotly.express as px

px.scatter(x=df.index, y=df[0])

In [8]:
import plotly.express as px

px.scatter(x=df_test.index, y=df_test[0])

In [9]:
def create_dataset_from_dataframe(
    raw_df: pd.DataFrame,
    input_feature_columns: list[int],
    label_column: int,
    input_width: int,
    label_width: int,
    label_offset: int,
    batch_size: int = 32,
) -> tf.data.Dataset:
    total_width = input_width + label_offset + label_width - 1
    label_start = input_width + label_offset - 1
    label_column_index = [
        i for i, column in enumerate(df.columns) if column == label_column
    ]
    feature_column_index = [
        i for i, column in enumerate(df.columns) if column in input_feature_columns
    ]
    time_column_index = [i for i, column in enumerate(df.columns) if column == "time"]
    data = tf.keras.utils.timeseries_dataset_from_array(
        data=raw_df,
        targets=None,
        sequence_length=total_width,
        sequence_stride=1,
        batch_size=batch_size,
        shuffle=False,
    )

    def split_dataset(data) -> tuple[tf.data.Dataset, tf.data.Dataset]:
        input_column_index_tensor = tf.constant(feature_column_index, dtype=tf.int32)
        label_column_index_tensor = tf.constant(label_column_index, dtype=tf.int32)
        time_column_index_tensor = tf.constant(time_column_index, dtype=tf.int32)
        input = tf.gather(
            data[:, slice(0, input_width), :], input_column_index_tensor, axis=-1
        )
        label = tf.gather(
            data[:, slice(label_start, None), :], label_column_index_tensor, axis=-1
        )
        input_time = tf.gather(
            data[:, slice(0, input_width), :], time_column_index_tensor, axis=-1
        )
        label_time = tf.gather(
            data[:, slice(label_start, None), :], time_column_index_tensor, axis=-1
        )
        input.set_shape([None, input_width, len(feature_column_index)])
        label.set_shape([None, label_width, len(label_column_index)])
        input_time.set_shape([None, input_width, 1])
        label_time.set_shape([None, label_width, 1])

        # print(input_time.shape)
        # input_time.set_shape([None, input_width, 1])
        # label_time.set_shape([None, label_width, 1])
        return (input, input_time), (label, label_time)
        # return input, label

    return data.map(split_dataset)

df["time"] = df.index
input_feature_columns = [col for col in df.columns if col != "time"]
input_width = 100
label_column = 0
label_width = 1
label_offset = 1
train_dataset = create_dataset_from_dataframe(
    df, input_feature_columns, label_column, input_width, label_width, label_offset
)
train_size = int(0.8 * len(train_dataset))
val_data = train_dataset.skip(train_size)
train_data = train_dataset.take(train_size)
train_dataset.element_spec

((TensorSpec(shape=(None, 100, 25), dtype=tf.float64, name=None),
  TensorSpec(shape=(None, 100, 1), dtype=tf.float64, name=None)),
 (TensorSpec(shape=(None, 1, 1), dtype=tf.float64, name=None),
  TensorSpec(shape=(None, 1, 1), dtype=tf.float64, name=None)))

In [10]:
class MyModel(tf.keras.Model):

    def __init__(self, base_model: tf.keras.Model):
        super().__init__()
        self.base_model = base_model

    def call(self, features: tf.data.Dataset, training: bool = False):
        return self.base_model(features, training=training)
    
    def train_step(self, train_data: tf.data.Dataset):
        """
        Runs one step of training. It is called by the fit method of tf.keras.Model.


        """
        (features, _), (labels, _) = train_data
        # features, labels = train_data

        with tf.GradientTape() as tape:
            y_pred = self(features, training=True)
            loss = self.compiled_loss(labels, y_pred)
        
        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
        # self.compiled_metrics.update_state(labels, y_pred)
        for metric in self.metrics:
            metric.update_state(labels, y_pred)

        return {m.name: m.result() for m in self.metrics}

multi_step_dense = tf.keras.Sequential(
    [
        # Shape: (time, features) => (time*features)
        tf.keras.layers.Flatten(input_shape=(input_width, 25)),
        tf.keras.layers.Dense(units=32, activation="relu"),
        tf.keras.layers.Dense(units=32, activation="relu"),
        tf.keras.layers.Dense(units=1),
        # Add back the time dimension.
        # Shape: (outputs) => (1, outputs)
        tf.keras.layers.Reshape([1, -1]),
        # tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, axis=1))
    ]
)
my_model = MyModel(multi_step_dense)
patience = 2
MAX_EPOCHS = 20

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=patience, mode="min"
)

my_model.compile(
    loss=tf.keras.losses.MeanSquaredError(),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=[tf.keras.metrics.MeanAbsoluteError()],
)

history = my_model.fit(
    train_data, epochs=MAX_EPOCHS, )
# validation_data=val_data, callbacks=[early_stopping]
# )

Epoch 1/20

/Users/shelleygoel/Code/THOC-Pytorch/.venv/lib/python3.9/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

/Users/shelleygoel/Code/THOC-Pytorch/.venv/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py:667: UserWarning:

`model.compiled_loss()` is deprecated. Instead, use `model.compute_loss(x, y, y_pred, sample_weight, training)`.

69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - mean_absolute_error: 0.6042 - loss: -1.0906
Epoch 2/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.1792 - loss: -1.6164
Epoch 3/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.1225 - loss: -1.7210
Epoch 4/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - mean_absolute_error: 0.0912 - loss: -1.7688
Epoch 5/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - mean_absolute_error: 0.0723 - loss: -1.7992
Epoch 6/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0618 - loss: -1.8136
Epoch 7/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0528 - loss: -1.8148
Epoch 8/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0459 - loss: -1.8361
Epoch 9/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0408 - loss: -1.8547
Epoch 10/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0380 - loss: -1.8500
Epoch 11/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0356 - loss: -1.8530
Epoch 12/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0329 - loss: -1.8562
Epoch 13/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0349 - loss: -1.8592
Epoch 14/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0364 - loss: -1.8639
Epoch 15/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0418 - loss: -1.8357
Epoch 16/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0475 - loss: -1.8531
Epoch 17/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0496 - loss: -1.8182
Epoch 18/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0494 - loss: -1.8739
Epoch 19/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0432 - loss: -1.8521
Epoch 20/20
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - mean_absolute_error: 0.0344 - loss: -1.8608

In [11]:
def get_batch_predictions(test_dataset: tf.data.Dataset) -> pd.DataFrame:
    test_pred_df_list = []

    for batch in test_dataset:
        (test_features, test_features_time), (test_labels, test_labels_time) = batch
        y_test_pred = my_model(test_features)
        df_test_pred = pd.DataFrame({
            'time': test_labels_time.numpy().reshape((-1)),
            'label': test_labels.numpy().reshape((-1)),
            'pred': y_test_pred.numpy().reshape((-1)),
        })
        test_pred_df_list.append(df_test_pred)

    test_pred_df = pd.concat(test_pred_df_list)
    return test_pred_df

In [12]:

df_test["time"] = df_test.index
test_dataset = create_dataset_from_dataframe(
    df_test,input_feature_columns, label_column, input_width, label_width, label_offset, batch_size=1000
)
test_pred_df = get_batch_predictions(test_dataset)

2025-01-17 08:12:28.448514: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [13]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=test_pred_df["time"], y=test_pred_df["pred"], mode='markers', name='pred'))
fig.add_trace(go.Scatter(x=test_pred_df["time"], y=test_pred_df["label"], mode='markers+lines', name='actual'))
# px.scatter(df_test_pred, x="time", y="label")

In [15]:
train_pred_df = get_batch_predictions(train_data)
fig = go.Figure()
fig.add_trace(go.Scatter(x=train_pred_df["time"], y=train_pred_df["pred"], mode='markers', name='pred'))
fig.add_trace(go.Scatter(x=train_pred_df["time"], y=train_pred_df["label"], mode='markers+lines', name='actual'))

In [16]:
train_pred_df

      time  label      pred
0    100.0   -1.0 -0.968289
1    101.0   -1.0 -0.976333
2    102.0   -1.0 -0.960262
3    103.0   -1.0 -0.935995
4    104.0   -1.0 -0.996138
..     ...    ...       ...
27  2303.0   -1.0 -0.978364
28  2304.0   -1.0 -0.973718
29  2305.0   -1.0 -1.004868
30  2306.0   -1.0 -0.998463
31  2307.0   -1.0 -1.048508

[2208 rows x 3 columns]