In [1]:
import tensorflow as tf
import numpy as np

# Prepare Dataset for input into the model

In [2]:
import pandas as pd
from pathlib import Path
labeled_anomalies = pd.read_csv(Path("/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/labeled_anomalies.csv"))
labeled_anomalies
labeled_anomalies.groupby("spacecraft")["chan_id"].nunique()

spacecraft
MSL     27
SMAP    54
Name: chan_id, dtype: int64

In [21]:
import numpy as np
for i, row in labeled_anomalies.iterrows():
    ch_id = labeled_anomalies["chan_id"][i]
    ch_data = np.load(Path(f"/Users/shelleygoel/Code/THOC-Pytorch/msl_smap_data/train/{ch_id}.npy"))
    print(row["spacecraft"], ch_id, ch_data.shape)

SMAP P-1 (2872, 25)
SMAP S-1 (2818, 25)
SMAP E-1 (2880, 25)
SMAP E-2 (2880, 25)
SMAP E-3 (2880, 25)
SMAP E-4 (2880, 25)
SMAP E-5 (2880, 25)
SMAP E-6 (2880, 25)
SMAP E-7 (2769, 25)
SMAP E-8 (2880, 25)
SMAP E-9 (2880, 25)
SMAP E-10 (2880, 25)
SMAP E-11 (2880, 25)
SMAP E-12 (2880, 25)
SMAP E-13 (2880, 25)
SMAP A-1 (2880, 25)
SMAP D-1 (2849, 25)
SMAP P-2 (2821, 25)
SMAP P-3 (2855, 25)
SMAP D-2 (2880, 25)
SMAP D-3 (2880, 25)
SMAP D-4 (2833, 25)
SMAP A-2 (2648, 25)
SMAP A-3 (2736, 25)
SMAP A-4 (2690, 25)
SMAP G-1 (2820, 25)
SMAP G-2 (2478, 25)
SMAP D-5 (2561, 25)
SMAP D-6 (2594, 25)
SMAP D-7 (2583, 25)
SMAP F-1 (2869, 25)
SMAP P-4 (2609, 25)
SMAP G-3 (2624, 25)
SMAP T-1 (2875, 25)
SMAP T-2 (2855, 25)
SMAP D-8 (2602, 25)
SMAP D-9 (2583, 25)
SMAP F-2 (2861, 25)
SMAP G-4 (2551, 25)
SMAP T-3 (2876, 25)
SMAP D-11 (2611, 25)
SMAP D-12 (312, 25)
SMAP B-1 (2435, 25)
SMAP G-6 (2881, 25)
SMAP G-7 (2446, 25)
SMAP P-7 (2853, 25)
SMAP R-1 (2874, 25)
SMAP A-5 (705, 25)
SMAP A-6 (682, 25)
SMAP A-7 (2879, 25)
SMAP D-13 (1490, 25)
SMAP P-2 (2821, 25)
SMAP A-8 (762, 25)
SMAP A-9 (762, 25)
SMAP F-3 (2880, 25)
MSL M-6 (1565, 55)
MSL M-1 (2209, 55)
MSL M-2 (2208, 55)
MSL S-2 (926, 55)
MSL P-10 (4308, 55)
MSL T-4 (2272, 55)
MSL T-5 (2272, 55)
MSL F-7 (2511, 55)
MSL M-3 (2037, 55)
MSL M-4 (2076, 55)
MSL M-5 (2032, 55)
MSL P-15 (3682, 55)
MSL C-1 (2158, 55)
MSL C-2 (764, 55)
MSL T-12 (1145, 55)
MSL T-13 (1145, 55)
MSL F-4 (2244, 55)
MSL F-5 (2598, 55)
MSL D-14 (3675, 55)
MSL T-9 (439, 55)
MSL P-14 (2880, 55)
MSL T-8 (748, 55)
MSL P-11 (3969, 55)
MSL D-15 (2074, 55)
MSL D-16 (1451, 55)
MSL M-7 (1587, 55)
MSL F-8 (3342, 55)

In [4]:
df = pd.DataFrame(ch_data)
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
count,3342.000000,3342.0,3342.0,3342.0,3342.0,3342.000000,3342.0,3342.0,3342.0,3342.0,...,3342.0,3342.0,3342.000000,3342.0,3342.0,3342.0,3342.0,3342.0,3342.000000,3342.000000
mean,-0.791312,0.0,0.0,0.0,0.0,0.033513,0.0,0.0,0.0,0.0,...,0.0,0.0,0.013166,0.0,0.0,0.0,0.0,0.0,0.000299,0.000898
std,0.493344,0.0,0.0,0.0,0.0,0.179998,0.0,0.0,0.0,0.0,...,0.0,0.0,0.114001,0.0,0.0,0.0,0.0,0.0,0.017298,0.029952
min,-1.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
25%,-1.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
50%,-1.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
75%,-0.913043,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
max,1.130435,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.000000,1.000000

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,-0.826087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.869565,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.869565,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.782609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-0.869565,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.shape

(3342, 55)

In [7]:
3342/7

477.42857142857144

In [15]:
input_width = 5
label_width = 1
label_offset = 1
total_width= input_width + label_offset + label_width - 1
label_start = input_width + label_offset - 1
train_data = tf.keras.utils.timeseries_dataset_from_array(
    data=df,
    targets=None,
    sequence_length=total_width,
    sequence_stride=1,
    batch_size=32,
    shuffle=True,

)

def split_dataset(data) -> tuple[tf.data.Dataset, tf.data.Dataset]:
    input = data[: , slice(0, input_width), :]
    label = data[:, slice(label_start, None), :]
    return input, label

train_dataset = train_data.map(split_dataset)

In [ ]:
input_slice = np.arange(i)

In [17]:
for input, target in train_dataset:
    print(input.shape)
    print(target.shape)

(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(32, 5, 55)
(32, 1, 55)
(9, 5, 55)
(9, 1, 55)

2025-01-13 12:07:24.648440: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [18]:
linear = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1)
])

In [19]:
MAX_EPOCHS = 20

def compile_and_fit(model, train_dataset, patience=2):
  early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss',
                                                    patience=patience,
                                                    mode='min')

  model.compile(loss=tf.keras.losses.MeanSquaredError(),
                optimizer=tf.keras.optimizers.Adam(),
                metrics=[tf.keras.metrics.MeanAbsoluteError()])

  history = model.fit(train_dataset, epochs=MAX_EPOCHS,
                      validation_data=train_dataset,
                      callbacks=[early_stopping])
  return history

history = compile_and_fit(linear, train_dataset)

Epoch 1/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0358 - mean_absolute_error: 0.1327 - val_loss: 0.0211 - val_mean_absolute_error: 0.0554
Epoch 2/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0204 - mean_absolute_error: 0.0477 - val_loss: 0.0192 - val_mean_absolute_error: 0.0377
Epoch 3/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0191 - mean_absolute_error: 0.0380 - val_loss: 0.0184 - val_mean_absolute_error: 0.0370
Epoch 4/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0184 - mean_absolute_error: 0.0366 - val_loss: 0.0180 - val_mean_absolute_error: 0.0354
Epoch 5/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0179 - mean_absolute_error: 0.0350 - val_loss: 0.0178 - val_mean_absolute_error: 0.0340
Epoch 6/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0177 - mean_absolute_error: 0.0335 - val_loss: 0.0176 - val_mean_absolute_error: 0.0329
Epoch 7/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0177 - mean_absolute_error: 0.0326 - val_loss: 0.0176 - val_mean_absolute_error: 0.0320
Epoch 8/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0175 - mean_absolute_error: 0.0318 - val_loss: 0.0176 - val_mean_absolute_error: 0.0316
Epoch 9/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0315 - val_loss: 0.0175 - val_mean_absolute_error: 0.0311
Epoch 10/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0175 - mean_absolute_error: 0.0310 - val_loss: 0.0175 - val_mean_absolute_error: 0.0309
Epoch 11/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0308 - val_loss: 0.0175 - val_mean_absolute_error: 0.0313
Epoch 12/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0175 - mean_absolute_error: 0.0309 - val_loss: 0.0175 - val_mean_absolute_error: 0.0310
Epoch 13/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0311 - val_loss: 0.0175 - val_mean_absolute_error: 0.0307
Epoch 14/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0175 - mean_absolute_error: 0.0307 - val_loss: 0.0175 - val_mean_absolute_error: 0.0311
Epoch 15/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0311 - val_loss: 0.0175 - val_mean_absolute_error: 0.0313
Epoch 16/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0175 - mean_absolute_error: 0.0308 - val_loss: 0.0175 - val_mean_absolute_error: 0.0312
Epoch 17/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0311 - val_loss: 0.0175 - val_mean_absolute_error: 0.0312
Epoch 18/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0310 - val_loss: 0.0175 - val_mean_absolute_error: 0.0308
Epoch 19/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0307 - val_loss: 0.0175 - val_mean_absolute_error: 0.0311
Epoch 20/20
105/105 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0176 - mean_absolute_error: 0.0309 - val_loss: 0.0175 - val_mean_absolute_error: 0.0306

In [20]:
history